spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: SpringMVC_Thymeleaf
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      platform: postgresql
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#      mode: always
sql:
  sqlFindAll: "SELECT * FROM userTable"
  sqlSave: "INSERT INTO userTable (firstName, lastName) VALUES (?, ?)"
  sqlDeleteById: "DELETE FROM userTable WHERE id=?"
  sqlUpdateUser: "UPDATE userTable SET firstName = ?, lastName = ? WHERE id = ?"
  sqlGetOne: "SELECT * FROM userTable WHERE id = "
